import 'dart:async';

import 'package:flutter/material.dart';
import 'package:app/core/constants/localization_keys.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  Future<bool> load() async {
    // Parse the JSON and store in _localizedStrings
    // For now, we'll use a simple approach
    _localizedStrings = _mapLanguageToStrings(locale.languageCode);
    return true;
  }

  Map<String, String> _mapLanguageToStrings(String languageCode) {
    switch (languageCode) {
      case 'ru':
        return {
          LocalizationKeys.appTitle: 'Omirtai Color',
          LocalizationKeys.home: 'Главная',
          LocalizationKeys.colors: 'Цвета',
          LocalizationKeys.calculators: 'Калькуляторы',
          LocalizationKeys.settings: 'Настройки',
          LocalizationKeys.showBottomNavBar: 'Показать нижнюю панель навигации',
          LocalizationKeys.showDrawerNav: 'Показать боковую панель навигации',
          LocalizationKeys.theme: 'Тема',
          LocalizationKeys.lightTheme: 'Светлая',
          LocalizationKeys.darkTheme: 'Темная',
          LocalizationKeys.systemTheme: 'Системная',
          LocalizationKeys.language: 'Язык',
          LocalizationKeys.settingsNote: 'Изменения настроек вступают в силу немедленно.',
          LocalizationKeys.homeScreen: 'Домашний экран',
          LocalizationKeys.colorsScreen: 'Экран цветов',
          LocalizationKeys.calculatorsScreen: 'Экран калькуляторов',
          LocalizationKeys.settingsScreen: 'Экран настроек',
          LocalizationKeys.modelingScreen: '3D Моделирование',
          LocalizationKeys.navigation: 'Навигация',
          // Screen descriptions
          LocalizationKeys.homeScreenDescription: 'Добро пожаловать в Omirtai Color. Здесь вы найдете все необходимые инструменты для работы с цветом.',
          LocalizationKeys.colorsScreenDescription: 'Изучайте и управляйте своими цветовыми палитрами с помощью интуитивных цветовых инструментов.',
          LocalizationKeys.calculatorsScreenDescription: 'Доступ к мощным вычислительным инструментам для всех ваших математических потребностей.',
          LocalizationKeys.modelingScreenDescription: 'Просматривайте и взаимодействуйте с 3D-моделями с помощью наших передовых инструментов моделирования.',
          LocalizationKeys.areaCalculator: 'Калькулятор площади',
          LocalizationKeys.volumeCalculator: 'Калькулятор объема',
          LocalizationKeys.length: 'Длина',
          LocalizationKeys.width: 'Ширина',
          LocalizationKeys.height: 'Высота',
          LocalizationKeys.depth: 'Глубина',
          LocalizationKeys.calculateArea: 'Рассчитать площадь',
          LocalizationKeys.calculateVolume: 'Рассчитать объем',
          LocalizationKeys.result: 'Результат',
          LocalizationKeys.squareMeters: 'Квадратные метры',
          LocalizationKeys.cubicMeters: 'Кубические метры',
          LocalizationKeys.enterValidNumbers: 'Пожалуйста, введите допустимые числа',
          LocalizationKeys.areaResult: 'Площадь: {result} м²',
          LocalizationKeys.volumeResult: 'Объем: {result} м³',
          LocalizationKeys.count: 'Количество',
          LocalizationKeys.pricePerM2: 'Цена за м²',
          LocalizationKeys.totalPrice: 'Общая цена',
          LocalizationKeys.addEntry: 'Добавить запись',
          LocalizationKeys.removeEntry: 'Удалить',
          LocalizationKeys.calculate: 'Рассчитать',
          LocalizationKeys.heightMm: 'Высота (мм)',
          LocalizationKeys.widthMm: 'Ширина (мм)',
          LocalizationKeys.area: 'Площадь',
          LocalizationKeys.totalArea: 'Общая площадь',
          LocalizationKeys.depthMm: 'Глубина (мм)',
          LocalizationKeys.pricePerM3: 'Цена за м³',
          LocalizationKeys.totalVolume: 'Общий объем',
          LocalizationKeys.volume: 'Объем',
          LocalizationKeys.cubicMetersWithValue: '{value} м³',
          LocalizationKeys.lengthMm: 'Длина (мм)',
          LocalizationKeys.totalCount: 'Общее количество',
          LocalizationKeys.summary: 'Сводка',
          LocalizationKeys.entry: 'Запись',
          LocalizationKeys.editEntry: 'Редактировать запись',
          LocalizationKeys.updateEntry: 'Обновить запись',
          LocalizationKeys.cancel: 'Отмена',
          LocalizationKeys.actions: 'Действия',
          LocalizationKeys.delete: 'Удалить',
          LocalizationKeys.deleteSelected: 'Удалить выбранные',
          LocalizationKeys.selectAll: 'Выбрать все',
          LocalizationKeys.clearSelection: 'Очистить выбор',
          LocalizationKeys.selectedEntries: 'Выбрано записей: {count}',
          LocalizationKeys.confirmDelete: 'Подтвердить удаление',
          LocalizationKeys.confirmDeleteSelectedEntries: 'Вы уверены, что хотите удалить {count} записей?',
          LocalizationKeys.edit: 'Редактировать',
          LocalizationKeys.squareMetersWithValue: '{value} м²',
          LocalizationKeys.currencyValue: '{value}',
          LocalizationKeys.history: 'История',
          LocalizationKeys.saveToHistory: 'Сохранить в истории',
          LocalizationKeys.savedToHistory: 'Сохранено в истории',
          LocalizationKeys.errorSavingHistory: 'Ошибка сохранения истории',
          LocalizationKeys.noEntriesToSave: 'Нет записей для сохранения',
          LocalizationKeys.historyEntry: 'Запись истории',
          LocalizationKeys.noHistoryEntries: 'Пока нет записей в истории',
          LocalizationKeys.clearHistory: 'Очистить историю',
          LocalizationKeys.confirmClearHistory: 'Очистить историю',
          LocalizationKeys.confirmClearAllHistory: 'Вы уверены, что хотите очистить всю историю?',
          LocalizationKeys.historyCleared: 'История очищена',
          LocalizationKeys.errorClearingHistory: 'Ошибка очистки истории',
          LocalizationKeys.confirmDeleteHistoryEntry: 'Вы уверены, что хотите удалить эту запись истории?',
          LocalizationKeys.historyEntryDeleted: 'Запись истории удалена',
          LocalizationKeys.errorDeletingHistory: 'Ошибка удаления записи истории',
          LocalizationKeys.entryCount: 'Записи',
          LocalizationKeys.clear: 'Очистить',
          LocalizationKeys.colorCode: 'Код цвета',
          LocalizationKeys.colorName: 'Название цвета',
          LocalizationKeys.colorGroup: 'Группа цвета',
          LocalizationKeys.colorCollection: 'Коллекция цвета',
          LocalizationKeys.colorValues: 'Значения цвета',
          LocalizationKeys.hexValue: 'HEX',
          LocalizationKeys.rgbValue: 'RGB',
          LocalizationKeys.rgbaValue: 'RGBA',
          LocalizationKeys.hslValue: 'HSL',
          LocalizationKeys.hsvValue: 'HSV',
          LocalizationKeys.xyzValue: 'XYZ',
          LocalizationKeys.labValue: 'LAB',
          LocalizationKeys.searchHint: 'Поиск по названию, коду или HEX значению...',
          LocalizationKeys.retry: 'Повторить',
          LocalizationKeys.navigationWarning: 'Должна быть включена хотя бы одна опция навигации',
          // Modeling
          LocalizationKeys.roomSettings: 'Настройки комнаты',
          LocalizationKeys.roomDimensions: 'Размеры комнаты',
          LocalizationKeys.roomWidth: 'Ширина',
          LocalizationKeys.roomDepth: 'Глубина',
          LocalizationKeys.roomHeight: 'Высота',
          LocalizationKeys.surfaceColors: 'Цвета поверхностей',
          LocalizationKeys.floorColor: 'Цвет пола',
          LocalizationKeys.ceilingColor: 'Цвет потолка',
          LocalizationKeys.wallColor: 'Цвет стен',
          LocalizationKeys.resetToDefault: 'Сбросить',
          LocalizationKeys.selectColor: 'Выбрать цвет',
          LocalizationKeys.selectTexture: 'Выбрать текстуру',
          LocalizationKeys.close: 'Закрыть',
          LocalizationKeys.modelLoadingError: 'Не удалось загрузить 3D модель',
          LocalizationKeys.modelLoadingErrorDescription: 'Пожалуйста, проверьте подключение к интернету и попробуйте снова',
          LocalizationKeys.retryWithAsset: 'Попробовать с локальным файлом',
          LocalizationKeys.usingAssetModelInfo: 'Используется локальная модель',
          LocalizationKeys.roomModelAlt: '3D Модель комнаты',
          LocalizationKeys.errorLoadingRalColors: 'Ошибка загрузки цветов RAL',
          LocalizationKeys.noneTexture: 'Нет',
          LocalizationKeys.predefinedColorsTitle: 'Предопределенные цвета для выбора',
          LocalizationKeys.errorLoadingColors: 'Ошибка загрузки цветов: {error}',
          LocalizationKeys.englishLanguage: 'English',
          LocalizationKeys.russianLanguage: 'Русский',
          LocalizationKeys.kazakhLanguage: 'Қазақша',
          LocalizationKeys.colorCodeLabel: 'Код',
          LocalizationKeys.colorNameLabel: 'Название',
          LocalizationKeys.colorGroupLabel: 'Группа',
          LocalizationKeys.colorCollectionLabel: 'Коллекция',
          LocalizationKeys.colorValuesLabel: 'Значения',
          LocalizationKeys.hexValueLabel: 'HEX',
          LocalizationKeys.rgbValueLabel: 'RGB',
          LocalizationKeys.rgbaValueLabel: 'RGBA',
          LocalizationKeys.hslValueLabel: 'HSL',
          LocalizationKeys.hsvValueLabel: 'HSV',
          LocalizationKeys.xyzValueLabel: 'XYZ',
          LocalizationKeys.labValueLabel: 'LAB',
          // Color value formats
          LocalizationKeys.rgbFormat: 'R: {r}, G: {g}, B: {b}',
          LocalizationKeys.rgbaFormat: 'R: {r}, G: {g}, B: {b}, A: {a}',
          LocalizationKeys.hslFormat: 'H: {h}°, S: {s}%, L: {l}%',
          LocalizationKeys.hsvFormat: 'H: {h}°, S: {s}%, V: {v}%',
          LocalizationKeys.xyzFormat: 'X: {x}, Y: {y}, Z: {z}',
          LocalizationKeys.labFormat: 'L: {l}, A: {a}, B: {b}',
        };
      case 'kk': // Kazakh translations
        return {
          LocalizationKeys.appTitle: 'Omirtai Color',
          LocalizationKeys.home: 'Басты бет',
          LocalizationKeys.colors: 'Түстер',
          LocalizationKeys.calculators: 'Калькуляторлар',
          LocalizationKeys.settings: 'Параметрлер',
          LocalizationKeys.showBottomNavBar: 'Төменгі навигациялық панельді көрсету',
          LocalizationKeys.showDrawerNav: 'Шығармалы навигацияны көрсету',
          LocalizationKeys.theme: 'Тақырып',
          LocalizationKeys.lightTheme: 'Ашық',
          LocalizationKeys.darkTheme: 'Қараңғы',
          LocalizationKeys.systemTheme: 'Жүйе',
          LocalizationKeys.language: 'Тіл',
          LocalizationKeys.settingsNote: 'Параметрлерді өзгерту дереу қолданылады.',
          LocalizationKeys.homeScreen: 'Басты экран',
          LocalizationKeys.colorsScreen: 'Түстер экраны',
          LocalizationKeys.calculatorsScreen: 'Калькуляторлар экраны',
          LocalizationKeys.settingsScreen: 'Параметрлер экраны',
          LocalizationKeys.modelingScreen: '3D Модельдеу',
          LocalizationKeys.navigation: 'Навигация',
          // Screen descriptions
          LocalizationKeys.homeScreenDescription: 'Omirtai Color қолданбасына қош келдіңіз. Түстермен жұмыс істеуге арналған барлық қажетті құралдарды осында табасыз.',
          LocalizationKeys.colorsScreenDescription: 'Интуитивті түрлі құралдармен түстер палитраларын зерттеңіз және басқарыңыз.',
          LocalizationKeys.calculatorsScreenDescription: 'Барлық математикалық есептеулеріңіз үшін қуатты есептеу құралдарына кіріңіз.',
          LocalizationKeys.modelingScreenDescription: '3D модельдерді қарап шығыңыз және олармен әрекеттесіңіз.',
          LocalizationKeys.areaCalculator: 'Ауданды есептеу',
          LocalizationKeys.volumeCalculator: 'Көлемді есептеу',
          LocalizationKeys.length: 'Ұзындығы',
          LocalizationKeys.width: 'Ені',
          LocalizationKeys.height: 'Биіктігі',
          LocalizationKeys.depth: 'Тереңдігі',
          LocalizationKeys.calculateArea: 'Ауданды есептеу',
          LocalizationKeys.calculateVolume: 'Көлемді есептеу',
          LocalizationKeys.result: 'Нәтиже',
          LocalizationKeys.squareMeters: 'Шаршы метр',
          LocalizationKeys.cubicMeters: 'Шаршы метр куб',
          LocalizationKeys.enterValidNumbers: 'Жарамды сандарды енгізіңіз',
          LocalizationKeys.areaResult: 'Аудан: {result} м²',
          LocalizationKeys.volumeResult: 'Көлем: {result} м³',
          LocalizationKeys.count: 'Саны',
          LocalizationKeys.pricePerM2: 'м² бағасы',
          LocalizationKeys.totalPrice: 'Жалпы баға',
          LocalizationKeys.addEntry: 'Жазбаны қосу',
          LocalizationKeys.removeEntry: 'Жою',
          LocalizationKeys.calculate: 'Есептеу',
          LocalizationKeys.heightMm: 'Биіктігі (мм)',
          LocalizationKeys.widthMm: 'Ені (мм)',
          LocalizationKeys.area: 'Аудан',
          LocalizationKeys.totalArea: 'Жалпы аудан',
          LocalizationKeys.depthMm: 'Тереңдігі (мм)',
          LocalizationKeys.pricePerM3: 'м³ бағасы',
          LocalizationKeys.totalVolume: 'Жалпы көлем',
          LocalizationKeys.volume: 'Көлем',
          LocalizationKeys.cubicMetersWithValue: '{value} м³',
          LocalizationKeys.lengthMm: 'Ұзындығы (мм)',
          LocalizationKeys.totalCount: 'Жалпы сан',
          LocalizationKeys.summary: 'Қорытынды',
          LocalizationKeys.entry: 'Жазба',
          LocalizationKeys.editEntry: 'Жазбаны өңдеу',
          LocalizationKeys.updateEntry: 'Жазбаны жаңарту',
          LocalizationKeys.cancel: 'Болдырмау',
          LocalizationKeys.actions: 'Әрекеттер',
          LocalizationKeys.delete: 'Жою',
          LocalizationKeys.deleteSelected: 'Таңдалғандарды жою',
          LocalizationKeys.selectAll: 'Барлығын таңдау',
          LocalizationKeys.clearSelection: 'Таңдауды тазарту',
          LocalizationKeys.selectedEntries: 'Таңдалған жазбалар: {count}',
          LocalizationKeys.confirmDelete: 'Жоюды растау',
          LocalizationKeys.confirmDeleteSelectedEntries: 'Сіз шынымен {count} жазбаны жойғыңыз келе ме?',
          LocalizationKeys.edit: 'Өңдеу',
          LocalizationKeys.squareMetersWithValue: '{value} м²',
          LocalizationKeys.currencyValue: '{value}',
          LocalizationKeys.history: 'Тарих',
          LocalizationKeys.saveToHistory: 'Тарихқа сақтау',
          LocalizationKeys.savedToHistory: 'Тарихқа сақталды',
          LocalizationKeys.errorSavingHistory: 'Тарихты сақтау қатесі',
          LocalizationKeys.noEntriesToSave: 'Сақтау үшін жазбалар жоқ',
          LocalizationKeys.historyEntry: 'Тарих жазбасы',
          LocalizationKeys.noHistoryEntries: 'Әзірге тарих жазбалары жоқ',
          LocalizationKeys.clearHistory: 'Тарихты тазарту',
          LocalizationKeys.confirmClearHistory: 'Тарихты тазарту',
          LocalizationKeys.confirmClearAllHistory: 'Бүкіл тарихты тазартқыңыз келетініне сенімдісіз бе?',
          LocalizationKeys.historyCleared: 'Тарих тазартылды',
          LocalizationKeys.errorClearingHistory: 'Тарихты тазарту қатесі',
          LocalizationKeys.confirmDeleteHistoryEntry: 'Бұл тарих жазбасын жойғыңыз келетініне сенімдісіз бе?',
          LocalizationKeys.historyEntryDeleted: 'Тарих жазбасы жойылды',
          LocalizationKeys.errorDeletingHistory: 'Тарих жазбасын жою қатесі',
          LocalizationKeys.entryCount: 'Жазбалар',
          LocalizationKeys.clear: 'Тазарту',
          LocalizationKeys.colorCode: 'Түс коды',
          LocalizationKeys.colorName: 'Түс атауы',
          LocalizationKeys.colorGroup: 'Түс тобы',
          LocalizationKeys.colorCollection: 'Түс жинағы',
          LocalizationKeys.colorValues: 'Түс мәндері',
          LocalizationKeys.hexValue: 'HEX',
          LocalizationKeys.rgbValue: 'RGB',
          LocalizationKeys.rgbaValue: 'RGBA',
          LocalizationKeys.hslValue: 'HSL',
          LocalizationKeys.hsvValue: 'HSV',
          LocalizationKeys.xyzValue: 'XYZ',
          LocalizationKeys.labValue: 'LAB',
          LocalizationKeys.searchHint: 'Атауы, коды немесе HEX мәні бойынша іздеу...',
          LocalizationKeys.retry: 'Қайталау',
          LocalizationKeys.navigationWarning: 'Навигация опцияларының кем дегенде біреуі қосулы болуы керек',
          // Modeling
          LocalizationKeys.roomSettings: 'Бөлме параметрлері',
          LocalizationKeys.roomDimensions: 'Бөлме өлшемдері',
          LocalizationKeys.roomWidth: 'Ені',
          LocalizationKeys.roomDepth: 'Тереңдігі',
          LocalizationKeys.roomHeight: 'Биіктігі',
          LocalizationKeys.surfaceColors: 'Беттер түстері',
          LocalizationKeys.floorColor: 'Еден түсі',
          LocalizationKeys.ceilingColor: 'Шық түсі',
          LocalizationKeys.wallColor: 'Қабырға түсі',
          LocalizationKeys.resetToDefault: 'Қалпына келтіру',
          LocalizationKeys.selectColor: 'Түс таңдау',
          LocalizationKeys.selectTexture: 'Текстура таңдау',
          LocalizationKeys.close: 'Жабу',
          LocalizationKeys.modelLoadingError: '3D модельді жүктеу мүмкін болмады',
          LocalizationKeys.modelLoadingErrorDescription: 'Интернет байланысын тексеріп, қайталаңыз',
          LocalizationKeys.retryWithAsset: 'Жергілікті файлмен қайталау',
          LocalizationKeys.usingAssetModelInfo: 'Жергілікті модель қолданылуда',
          LocalizationKeys.roomModelAlt: '3D Бөлме моделі',
          LocalizationKeys.errorLoadingRalColors: 'RAL түстерін жүктеу қатесі',
          LocalizationKeys.noneTexture: 'Жоқ',
          LocalizationKeys.predefinedColorsTitle: 'Таңдау үшін алдын ала анықталған түстер',
          LocalizationKeys.errorLoadingColors: 'Түстерді жүктеу қатесі: {error}',
          LocalizationKeys.englishLanguage: 'English',
          LocalizationKeys.russianLanguage: 'Русский',
          LocalizationKeys.kazakhLanguage: 'Қазақша',
          LocalizationKeys.colorCodeLabel: 'Код',
          LocalizationKeys.colorNameLabel: 'Атауы',
          LocalizationKeys.colorGroupLabel: 'Топ',
          LocalizationKeys.colorCollectionLabel: 'Жинақ',
          LocalizationKeys.colorValuesLabel: 'Мәндер',
          LocalizationKeys.hexValueLabel: 'HEX',
          LocalizationKeys.rgbValueLabel: 'RGB',
          LocalizationKeys.rgbaValueLabel: 'RGBA',
          LocalizationKeys.hslValueLabel: 'HSL',
          LocalizationKeys.hsvValueLabel: 'HSV',
          LocalizationKeys.xyzValueLabel: 'XYZ',
          LocalizationKeys.labValueLabel: 'LAB',
          // Color value formats
          LocalizationKeys.rgbFormat: 'R: {r}, G: {g}, B: {b}',
          LocalizationKeys.rgbaFormat: 'R: {r}, G: {g}, B: {b}, A: {a}',
          LocalizationKeys.hslFormat: 'H: {h}°, S: {s}%, L: {l}%',
          LocalizationKeys.hsvFormat: 'H: {h}°, S: {s}%, V: {v}%',
          LocalizationKeys.xyzFormat: 'X: {x}, Y: {y}, Z: {z}',
          LocalizationKeys.labFormat: 'L: {l}, A: {a}, B: {b}',
        };
      case 'en':
      default:
        return {
          LocalizationKeys.appTitle: 'Omirtai Color',
          LocalizationKeys.home: 'Home',
          LocalizationKeys.colors: 'Colors',
          LocalizationKeys.calculators: 'Calculators',
          LocalizationKeys.settings: 'Settings',
          LocalizationKeys.showBottomNavBar: 'Show Bottom Navigation Bar',
          LocalizationKeys.showDrawerNav: 'Show Drawer Navigation',
          LocalizationKeys.theme: 'Theme',
          LocalizationKeys.lightTheme: 'Light',
          LocalizationKeys.darkTheme: 'Dark',
          LocalizationKeys.systemTheme: 'System',
          LocalizationKeys.language: 'Language',
          LocalizationKeys.settingsNote: 'Changes to settings take effect immediately.',
          LocalizationKeys.homeScreen: 'Home Screen',
          LocalizationKeys.colorsScreen: 'Colors Screen',
          LocalizationKeys.calculatorsScreen: 'Calculators Screen',
          LocalizationKeys.settingsScreen: 'Settings Screen',
          LocalizationKeys.modelingScreen: '3D Modeling',
          LocalizationKeys.navigation: 'Navigation',
          // Screen descriptions
          LocalizationKeys.homeScreenDescription: 'Welcome to Omirtai Color. Here you will find all the essential tools for working with color.',
          LocalizationKeys.colorsScreenDescription: 'Explore and manage your color palettes with our intuitive color tools.',
          LocalizationKeys.calculatorsScreenDescription: 'Access powerful calculation tools for all your mathematical needs.',
          LocalizationKeys.modelingScreenDescription: 'View and interact with 3D models using our advanced modeling tools.',
          LocalizationKeys.areaCalculator: 'Area Calculator',
          LocalizationKeys.volumeCalculator: 'Volume Calculator',
          LocalizationKeys.length: 'Length',
          LocalizationKeys.width: 'Width',
          LocalizationKeys.height: 'Height',
          LocalizationKeys.depth: 'Depth',
          LocalizationKeys.calculateArea: 'Calculate Area',
          LocalizationKeys.calculateVolume: 'Calculate Volume',
          LocalizationKeys.result: 'Result',
          LocalizationKeys.squareMeters: 'Square Meters',
          LocalizationKeys.cubicMeters: 'Cubic Meters',
          LocalizationKeys.enterValidNumbers: 'Please enter valid numbers',
          LocalizationKeys.areaResult: 'Area: {result} m²',
          LocalizationKeys.volumeResult: 'Volume: {result} m³',
          LocalizationKeys.count: 'Count',
          LocalizationKeys.pricePerM2: 'Price per m²',
          LocalizationKeys.totalPrice: 'Total Price',
          LocalizationKeys.addEntry: 'Add Entry',
          LocalizationKeys.removeEntry: 'Remove',
          LocalizationKeys.calculate: 'Calculate',
          LocalizationKeys.heightMm: 'Height (mm)',
          LocalizationKeys.widthMm: 'Width (mm)',
          LocalizationKeys.area: 'Area',
          LocalizationKeys.totalArea: 'Total Area',
          LocalizationKeys.depthMm: 'Depth (mm)',
          LocalizationKeys.pricePerM3: 'Price per m³',
          LocalizationKeys.totalVolume: 'Total Volume',
          LocalizationKeys.volume: 'Volume',
          LocalizationKeys.cubicMetersWithValue: '{value} m³',
          LocalizationKeys.lengthMm: 'Length (mm)',
          LocalizationKeys.totalCount: 'Total Count',
          LocalizationKeys.summary: 'Summary',
          LocalizationKeys.entry: 'Entry',
          LocalizationKeys.editEntry: 'Edit Entry',
          LocalizationKeys.updateEntry: 'Update Entry',
          LocalizationKeys.cancel: 'Cancel',
          LocalizationKeys.actions: 'Actions',
          LocalizationKeys.delete: 'Delete',
          LocalizationKeys.deleteSelected: 'Delete Selected',
          LocalizationKeys.selectAll: 'Select All',
          LocalizationKeys.clearSelection: 'Clear Selection',
          LocalizationKeys.selectedEntries: 'Selected entries: {count}',
          LocalizationKeys.confirmDelete: 'Confirm Delete',
          LocalizationKeys.confirmDeleteSelectedEntries: 'Are you sure you want to delete {count} entries?',
          LocalizationKeys.edit: 'Edit',
          LocalizationKeys.squareMetersWithValue: '{value} m²',
          LocalizationKeys.currencyValue: '{value}',
          LocalizationKeys.history: 'History',
          LocalizationKeys.saveToHistory: 'Save to History',
          LocalizationKeys.savedToHistory: 'Saved to history',
          LocalizationKeys.errorSavingHistory: 'Error saving history',
          LocalizationKeys.noEntriesToSave: 'No entries to save',
          LocalizationKeys.historyEntry: 'History Entry',
          LocalizationKeys.noHistoryEntries: 'No history entries yet',
          LocalizationKeys.clearHistory: 'Clear History',
          LocalizationKeys.confirmClearHistory: 'Clear History',
          LocalizationKeys.confirmClearAllHistory: 'Are you sure you want to clear all history?',
          LocalizationKeys.historyCleared: 'History cleared',
          LocalizationKeys.errorClearingHistory: 'Error clearing history',
          LocalizationKeys.confirmDeleteHistoryEntry: 'Are you sure you want to delete this history entry?',
          LocalizationKeys.historyEntryDeleted: 'History entry deleted',
          LocalizationKeys.errorDeletingHistory: 'Error deleting history entry',
          LocalizationKeys.entryCount: 'Entries',
          LocalizationKeys.clear: 'Clear',
          LocalizationKeys.colorCode: 'Color Code',
          LocalizationKeys.colorName: 'Color Name',
          LocalizationKeys.colorGroup: 'Color Group',
          LocalizationKeys.colorCollection: 'Color Collection',
          LocalizationKeys.colorValues: 'Color Values',
          LocalizationKeys.hexValue: 'HEX',
          LocalizationKeys.rgbValue: 'RGB',
          LocalizationKeys.rgbaValue: 'RGBA',
          LocalizationKeys.hslValue: 'HSL',
          LocalizationKeys.hsvValue: 'HSV',
          LocalizationKeys.xyzValue: 'XYZ',
          LocalizationKeys.labValue: 'LAB',
          LocalizationKeys.searchHint: 'Search by name, code, or hex value...',
          LocalizationKeys.retry: 'Retry',
          LocalizationKeys.navigationWarning: 'At least one navigation option must remain enabled',
          // Modeling
          LocalizationKeys.roomSettings: 'Room Settings',
          LocalizationKeys.roomDimensions: 'Room Dimensions',
          LocalizationKeys.roomWidth: 'Width',
          LocalizationKeys.roomDepth: 'Depth',
          LocalizationKeys.roomHeight: 'Height',
          LocalizationKeys.surfaceColors: 'Surface Colors',
          LocalizationKeys.floorColor: 'Floor Color',
          LocalizationKeys.ceilingColor: 'Ceiling Color',
          LocalizationKeys.wallColor: 'Wall Color',
          LocalizationKeys.resetToDefault: 'Reset to Default',
          LocalizationKeys.selectColor: 'Select Color',
          LocalizationKeys.selectTexture: 'Select Texture',
          LocalizationKeys.close: 'Close',
          LocalizationKeys.modelLoadingError: 'Failed to load 3D model',
          LocalizationKeys.modelLoadingErrorDescription: 'Please check your internet connection and try again',
          LocalizationKeys.retryWithAsset: 'Retry with local file',
          LocalizationKeys.usingAssetModelInfo: 'Using local model',
          LocalizationKeys.roomModelAlt: '3D Room Model',
          LocalizationKeys.errorLoadingRalColors: 'Error loading RAL colors',
          LocalizationKeys.noneTexture: 'None',
          LocalizationKeys.predefinedColorsTitle: 'Predefined colors for selection',
          LocalizationKeys.errorLoadingColors: 'Failed to load colors: {error}',
          LocalizationKeys.englishLanguage: 'English',
          LocalizationKeys.russianLanguage: 'Русский',
          LocalizationKeys.kazakhLanguage: 'Қазақша',
          LocalizationKeys.colorCodeLabel: 'Code',
          LocalizationKeys.colorNameLabel: 'Name',
          LocalizationKeys.colorGroupLabel: 'Group',
          LocalizationKeys.colorCollectionLabel: 'Collection',
          LocalizationKeys.colorValuesLabel: 'Values',
          LocalizationKeys.hexValueLabel: 'HEX',
          LocalizationKeys.rgbValueLabel: 'RGB',
          LocalizationKeys.rgbaValueLabel: 'RGBA',
          LocalizationKeys.hslValueLabel: 'HSL',
          LocalizationKeys.hsvValueLabel: 'HSV',
          LocalizationKeys.xyzValueLabel: 'XYZ',
          LocalizationKeys.labValueLabel: 'LAB',
          // Color value formats
          LocalizationKeys.rgbFormat: 'R: {r}, G: {g}, B: {b}',
          LocalizationKeys.rgbaFormat: 'R: {r}, G: {g}, B: {b}, A: {a}',
          LocalizationKeys.hslFormat: 'H: {h}°, S: {s}%, L: {l}%',
          LocalizationKeys.hsvFormat: 'H: {h}°, S: {s}%, V: {v}%',
          LocalizationKeys.xyzFormat: 'X: {x}, Y: {y}, Z: {z}',
          LocalizationKeys.labFormat: 'L: {l}, A: {a}, B: {b}',
        };
    }
  }

  String translate(String key) {
    return _localizedStrings[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ru', 'kk'].contains(locale.languageCode); // Added 'kk' for Kazakh
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    final AppLocalizations localizations = AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}




