# Codemagic CI/CD configuration for Omirtai Color application

# Set to true to run tests during build, false to skip tests
env:
  RUN_TESTS: false

workflows:
  ios-workflow:
    name: Omirtai Color iOS
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.35.6
      xcode: 15.2
      cocoapods: 1.15.2
    
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        # Removed ios/Pods from cache as it causes issues with paths
    
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
      cancel_previous_builds: true
    
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --enable-ios
          flutter pub get
      
      - name: Run tests
        script: |
          if [ "$RUN_TESTS" = true ]; then
            echo "Running tests..."
            flutter test
          else
            echo "Skipping tests as RUN_TESTS is set to false"
          fi
      
      - name: Set up code signing
        script: |
          echo "Setting up code signing..."
          # Code signing will be handled by Codemagic
          # You'll need to configure this in the Codemagic UI
      
      - name: Install and setup CocoaPods
        script: |
          echo "Installing and setting up CocoaPods using custom script..."
          # Make the script executable
          chmod +x ios/setup_cocoapods.sh
          # Run the script
          ./ios/setup_cocoapods.sh
      
      - name: Build iOS
        script: |
          echo "Building iOS app..."
          mkdir -p build/ios
          flutter build ios --release --no-codesign
      
      - name: Build IPA
        script: |
          echo "Creating IPA..."
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -destination generic/platform=iOS clean archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportPath $CM_BUILD_DIR/build/ios -exportOptionsPlist exportOptions.plist
    
    artifacts:
      - build/ios/*.ipa
      - build/ios/*.app
      - build/ios/*.dSYM
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - lokkitcdev@gmail.com
        notify:
          success: true
          failure: true