# Codemagic CI/CD configuration for Omirtai Color application

# Set to true to run tests during build, false to skip tests
env:
  RUN_TESTS: false

workflows:
  ios-workflow:
    name: Omirtai Color iOS
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.35.6
      xcode: 15.2
      cocoapods: 1.11.3  # Use compatible version
    
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        # Removed ios/Pods from cache as it causes issues with paths
    
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
      cancel_previous_builds: true
    
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --enable-ios
          flutter pub get
      
      - name: Run tests
        script: |
          if [ "$RUN_TESTS" = true ]; then
            echo "Running tests..."
            flutter test
          else
            echo "Skipping tests as RUN_TESTS is set to false"
          fi
      
      - name: Install and setup CocoaPods manually
        script: |
          echo "Installing and setting up CocoaPods manually..."
          # Make the script executable
          chmod +x ios/setup_cocoapods.sh
          # Run the script
          ./ios/setup_cocoapods.sh
          # Verify that pods were installed
          if [ -d "ios/Pods" ]; then
            echo "Pods directory exists:"
            ls -la ios/Pods/ | head -10
          else
            echo "ERROR: Pods directory not found!"
            exit 1
          fi
      
      - name: Build iOS
        script: |
          echo "Building iOS app..."
          mkdir -p build/ios
          # Skip pod install during build as we've already done it manually
          flutter build ios --release --no-codesign --no-pub
      
      - name: Build IPA (without code signing)
        script: |
          echo "Creating unsigned IPA..."
          cd ios
          # Create build directory if it doesn't exist
          mkdir -p build/ios
          # Build archive
          xcodebuild archive -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath Runner.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          # Export unsigned IPA
          xcodebuild -exportArchive -archivePath Runner.xcarchive -exportPath build/ios -exportOptionsPlist exportOptions.plist CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          # List files to verify IPA creation
          echo "Checking for IPA file..."
          ls -la build/ios/
          cd ..
    
    artifacts:
      - build/ios/*.ipa
      - build/ios/*.app
      - build/ios/*.dSYM
      - "*.xcarchive"
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - lokkitcdev@gmail.com
        notify:
          success: true
          failure: true